# Netlify Configuration for Utility Commission Claims

# Build settings
[build]
  command = "npm install && npm run build"
  publish = "dist"
  
# Build environment variables
[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"

# Redirects for single page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://www.google-analytics.com https://api.emailjs.com; frame-ancestors 'none';"

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form detection
[forms]
  mode = "netlify"

# Branch deploy settings
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }

# Redirect www to non-www
[[redirects]]
  from = "https://www.utilitycommissionclaims.co.uk/*"
  to = "https://utilitycommissionclaims.co.uk/:splat"
  status = 301
  force = true

# Redirect Netlify subdomain to primary domain
[[redirects]]
  from = "https://utility-commission-claims.netlify.app/*"
  to = "https://utilitycommissionclaims.co.uk/:splat"
  status = 301
  force = true